### ISSUE TITLE
Outdated: Magisk/AddonSU clickjacking

### ISSUE THREAD

**Issue by maniusq** [madaidans-insecurities/madaidans-insecurities.github.io#15]
I can't find any details about vulnerabilities related to Magisk/AddonSU. Do you have a link with an overview?

And in addition, because it matches the topic:

> It does not matter if you have to whitelist apps that have root — an attacker can fake user input by for example, clickjacking or they can exploit vulnerabilities in apps that you have granted root to.

Do you have an example for this? Unfortunately I have not found an example. It would be nice if they could give one or more CVE numbers for this, e.g. from here: https://www.cvedetails.com/product/19997/Google-Android.html?vendor_id=1224

**Comment by maniusq** [comment]
This information is outdated and affected all apps (e.g. banking, insurance,...), see https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-27059

Magisk has additional protection and does not grant root privileges while obscured by another window or overlay.

**Comment by maniusq** [comment]
All ROMs with patch level 2021-01-05 or higher are no longer affected, right?

**Comment by thestinger** [comment]
No, it's a generic class of issue, not a specific one as you seem to think. This is about systemic security not a specific bug, rather classes of bugs / weaknesses which can be exploited. The stuff you're talking about inherently turns a massive amount of the OS into attack surface granting root access rather than drastically less than that.

**Comment by madaidan** [comment]
The article is not referring to specific bugs, but rather the inherent attack surface posed by such modifications to the system. A single bug being fixed does not negate fundamental issues.

**Comment by maniusq** [comment]
Is there still a **clickjacking problem** when the clickjacking vulnerability in Android has been fixed and Magisk has built-in protection? How will this work then?

Please do not misunderstand. I'm just looking for a simple example that I can show to friends with a rooted Android. I want to trigger an "aha effect" in these people and that works best with practical and (unfortunately) not with theoretical knowledge.

Why is the issue closed???

**Comment by thestinger** [comment]
Clickjacking is still a class of vulnerability and also something that can be done by an accessibility service without any vulnerability. You keep talking as if these things are related to some specific issue / bug when that's not what this is about at all. You've had that pointed out to you repeatedly. You seem to be here to concern troll. I also really don't understand why you pinged me and brought me to this issue tracker.

**Comment by maniusq** [comment]
I can't find a practical example to show this to anyone else. I've written this in other comments as well, that I need something to show others who are rooting their devices. I can explain this to the other people as many times as I want, and I can also refer to this repository or the GrapheneOS FAQs as many times as I want. None of this works if people can't see it on a real example.

> You seem to be here to concern troll.

No, I'm definitely not a troll and I'm getting tired of this accusation. Not everyone who has a question or wants to understand something is a troll :-1: 

> I also really don't understand why you pinged me and brought me to this issue tracker.

I've written that here before as well. I enjoyed reading the replies [here](https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/issues/1#issuecomment-756867701), but I'm starting to get annoyed with being accused here.

**Comment by thestinger** [comment]
Click a link.

**Comment by thestinger** [comment]
An accessibility service. Any bug that gives that kind of control over the UI layer. Control over persistent state (you cannot have this and also have any meaningful verified boot to prevent persistent). If you've seen that linked thread you already have all the answers from that thread and can refer to it.

**Comment by thestinger** [comment]
> No, I'm definitely not a troll and I'm getting tired of this accusation. Not everyone who has a question or wants to understand something is a troll

You're repeatedly asking the same things and stating the same incorrect things. It really doesn't appear that you're here to ask questions in good faith. That's not the impression that you've given.

It's self-explanatory that if you have a way to provide persistent root access, that's stored in persistent state, and therefore verified boot doesn't work since the whole point of it is avoiding trust in persistent state. An attacker that has compromised the device simply gives themselves the access persistently. Same goes for control over the UI via accessibility service, clickjacking with or without a bug or a vulnerability giving any kind of control over the massive amount of attack surface you're trusting with root access. Any code execution vulnerability or even far less than that in anything that has been trusted with root gives persistent, unrevokable root access with that design.

**Comment by maniusq** [comment]
> You're repeatedly asking the same things and stating the same incorrect things. It really doesn't appear that you're here to ask questions in good faith. That's not the impression that you've given.

That was not my intention. I wanted to separate the topics as well as possible, so I only asked about the "clickjacking" problem here.

> It's self-explanatory that if you have a way to provide persistent root access, that's stored in persistent state, and therefore verified boot doesn't work since the whole point of it is avoiding trust in persistent state. An attacker that has compromised the device simply gives themselves the access persistently. Same goes for control over the UI via accessibility service, clickjacking with or without a bug or a vulnerability giving any kind of control over the massive amount of attack surface you're trusting with root access. Any code execution vulnerability or even far less than that in anything that has been trusted with root gives persistent, unrevokable root access with that design.

Okay, I already understand the first part. What I don't fully understand though is, you have to allow an app to have accessibility rights for that to be possible then, right? I think I installed such an app once (I think it was [Automagic](https://automagic4android.com/) that requested this right).

**Comment by thestinger** [comment]
> you have to allow an app to have accessibility rights for that to be possible then, right

No, you don't. Refer back to what was said in the entirety.

**Comment by maniusq** [comment]
> It's self-explanatory that if you have a way to provide persistent root access, that's stored in persistent state, and therefore verified boot doesn't work since the whole point of it is avoiding trust in persistent state. An attacker that has compromised the device simply gives themselves the access persistently.

This part is clear. I already knew that too.

> Same goes for control over the UI via accessibility service, clickjacking with or without a bug or a vulnerability giving any kind of control over the massive amount of attack surface you're trusting with root access. Any code execution vulnerability or even far less than that in anything that has been trusted with root gives persistent, unrevokable root access with that design.

Maybe a translation problem or because I imagine something different under this term. You mean with "accessibility service" apps, which are designed for people with a physical handicap or? These apps ask for permission first, don't they?

**Comment by thestinger** [comment]
> Maybe a translation problem or because I imagine something different under this term. You mean with "accessibility service" apps, which are designed for people with a physical handicap or? These apps ask for permission first, don't they?

It's a way to explicitly grant apps a bunch of power but it's in no way the only example. It's an example of this working by design without any vulnerability.

By trusting a massive portion of the OS with control over root access rather than a tiny portion, you're clearly massively expanding the attack surface and making a bunch of otherwise much less serious vulnerabilities such as very temporary control over the UI into persistent, unconstrained root access. Far more common, much less serious vulnerabilities are now as serious as it gets for a local vulnerability: local code execution with maximum privileges. That also makes remote vulnerabilities much more serious since the next step is escalating privileges, and now a huge portion of the OS has effective root access.

**Comment by madaidan** [comment]
@maniusq I suggest reading through the replies here and the website in full instead of consistently making unsubstantiated and untrue claims.
