### ISSUE TITLE
Clarify a bit better about the security purpose of the website

### ISSUE THREAD

**Issue by FieryBinary** [madaidans-insecurities/madaidans-insecurities.github.io#41]
The website is a great source of security/privacy information, but it only considers security/privacy and not other important things. That should be clarified a bit more, since for newcomers it can be confusing to see blatant stuff like "Do not use Linux". These kind of broad statements also invite more...interesting types that only consider security and nothing else. Considering how the website gets constantly hated on Reddit, clarifying the security purpose would probably reduce that too.

I realize it already has 

> Note that these analyses are purely objective and do not account for threat models or other user-dependent factors.

but you should still explicitly mention non-security stuff like performance.

Putting a disclaimer in the index.html, and in the security/privacy guide, like:

> This website only analyzes software security and privacy. It does not account for performance, usability, convenience, or anything else.

should be enough.

**Comment by 735trv** [comment]
> hated on Reddit

Maybe because it's not really objective. Some things are true, some things are wrong, some things are outdated:
* Some (not all) information about Flatpak are wrong or outdated.
* Disadvantages of Windows are missing.
* Advantages for Linux are missing.
* Advantages and disadvantages of macOS are missing. (own page)
* Advantages and disadvantages of iPhones are missing. (own page)
* There is also a missing hint that a sandbox does not provide 100% protection. There are always security holes through which one can break out of a sandbox. And because that happens all the time, a sandbox is not the holy grail. Nevertheless, it is good.
* The Android article is missing the note that no malware known so far has been tested on rooted devices. Any malware has gained root privileges on regular androids.
* Android: The part about verified boot is correct, but only important if an attacker has physical access to the device. Over-the-air attacks are not possible.
* Android Firewall: Bypassing Netguard or Afwall by IPC is no longer possible since Android 8. INTERNET permission is good, but has a limited feature set: Only allow/deny. No IP blocking. No domain blocking.

This repository is a good starting point, but not a substitute for doing your own research on specific topics. Some work is still needed to make this a good overview.

**Comment by FieryBinary** [comment]
@735trv What you're saying is very inaccurate. 

There are no significant advantages for Linux compared to Windows and macOS, hence why he doesn't have an article about that.

Not having certain articles is not misleading, it just means he hasn't gotten time to write them. He's covered macOS and Windows extensively in other articles anyway.

Just because a sandbox has vulnerabilities doesn't make it useless. Sandboxing is essential for security which you're downplaying.

Regarding Android, root makes exploiting the device much easier. That should be evident since the user is actively accessing root. Madaidan's article goes into detail about verified boot being about both physical and remote security, which you're completely ignoring. The INTERNET permission is the only proper and complete way to block internet, since otherwise apps can bypass it by sending data to different IP addresses/domains.

You haven't explained what's wrong with Flatpak or citing https://flatkill.org as a source.

I'd appreciate if you could keep this issue on track instead of making it about this. This issue is about clarifying that the website is about security/privacy and not anything else.

**Comment by 735trv** [comment]
> There are no significant advantages for Linux compared to Windows and macOS, hence why he doesn't have an article about that.

There will be at least one advantage 😉 The large number of Windows malware and the high distribution also increases the risk. But anyway, it would be very good for a good overall view.

> Just because a sandbox has vulnerabilities doesn't make it useless. Sandboxing is essential for security which you're downplaying.

I did not write that a sandbox is useless. I did not write that. Please read my sentences completely. An unexperienced user may get the impression that a sandbox is 100% safe. Exactly there is missing a small hint that a sandbox is not 100% safe but 99% safe.

> Regarding Android, root makes exploiting the device much easier. That should be evident since the user is actively accessing root. 

Yes, that's true of course. The Android malware we know use root access on devices that are not rooted (and do not ask for root privileges). That's the issue. People might get the impression that it's impossible for malware to get root privileges if the device isn't rooted, and that's not true.

> goes into detail about verified boot being about both physical and remote security

I've read this part, but I can't find any information about it on the Internet. Do you have a link where (except from physical access) is described or maybe a PoC? Probably not.

> The INTERNET permission is the only proper and complete way to block internet, since otherwise apps can bypass it by sending data to different IP addresses/domains.

Agree. In the article, a small note would be useful that this does not have the same functionality as other solutions. Btw: bypassing no longer works in Android >=8.

> You haven't explained what's outdated about Flatpak

Correct. For example the [sandbox permissions](https://docs.flatpak.org/en/latest/sandbox-permissions.html#sandbox-permissions).

> I'd appreciate if you could keep this issue on track instead of making it about this.

Ok.

**Comment by madaidans-insecurities** [comment]
I think the purpose of the website is already pretty clear, considering the writing on the home page, separate sections for security/privacy content, opening paragraph of each article and the fact it has "insecurities" in its name.
